# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations
from enum import Enum
from pydantic import AwareDatetime, BaseModel, Field, RootModel, confloat, conint, constr
from typing import Any, Literal


class Access(Enum):
    standing = "standing"
    break_glass = "break_glass"


class AdminUserListItem(BaseModel):
    created_at: AwareDatetime = Field(..., title="Created At")
    email: str = Field(..., title="Email")
    full_name: str = Field(..., title="Full Name")
    is_active: bool = Field(..., title="Is Active")
    is_verified: bool = Field(..., title="Is Verified")
    last_login_at: AwareDatetime | None = Field(None, title="Last Login At")
    organization_id: str = Field(..., title="Organization Id")
    roles: list[str] = Field(..., title="Roles")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")


class AdminUserListResponse(BaseModel):
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total: int = Field(..., title="Total")
    users: list[AdminUserListItem] = Field(..., title="Users")


class AttachmentResult(BaseModel):
    duplicate_of: str | None = Field(
        None,
        description="If set, this attachment was a per-case content-hash duplicate of an earlier upload. No new UploadedFile was created; this field carries the existing file_id. Frontend should render a non-blocking toast.",
        title="Duplicate Of",
    )
    duplicate_turn: int | None = Field(
        None,
        description="Turn number where the original was uploaded (for toast text).",
        title="Duplicate Turn",
    )
    file_id: str = Field(
        ..., description="UploadedFile row identifier for this attachment.", title="File Id"
    )
    file_size: int = Field(..., title="File Size")
    filename: str = Field(..., title="Filename")
    processing_status: str = Field(..., title="Processing Status")
    source_type: str = Field(
        ...,
        description="Data-type classification from preprocessing: logs | metrics | configuration | code | text | image",
        title="Source Type",
    )
    upload_source: str | None = Field(
        "file_upload",
        description="Input origin: file_upload | paste | page_capture | screenshot | agent_generated",
        title="Upload Source",
    )
    uploaded_at: str | None = Field(
        "",
        description="ISO 8601 timestamp of when the attachment was processed",
        title="Uploaded At",
    )


class AuthSessionCreateRequest(BaseModel):
    client_id: constr(min_length=1, max_length=255) | None = Field(
        None,
        description="Client/device identifier for session resumption. If provided, existing session for this client will be resumed.",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
        title="Client Id",
    )
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    session_type: constr(min_length=1) | None = Field("troubleshooting", title="Session Type")
    timeout_minutes: conint(ge=60, le=480) | None = Field(
        180,
        description="Session timeout in minutes. Min: 60 (1 hour), Max: 480 (8 hours), Default: 180 (3 hours)",
        examples=[180, 240, 360],
        title="Timeout Minutes",
    )


class AuthSessionStatus(Enum):
    active = "active"
    expired = "expired"
    terminated = "terminated"


class CodeChallengeMethodEnum(Enum):
    S256 = "S256"


class CodeChallengeMethod(RootModel[CodeChallengeMethodEnum | None]):
    root: CodeChallengeMethodEnum | None = Field("S256", title="Code Challenge Method")


class AuthorizationApprovalRequest(BaseModel):
    approved: bool = Field(
        ..., description="True if user approved, False if denied", title="Approved"
    )
    client_id: str = Field(..., description="OAuth client ID", title="Client Id")
    code_challenge: str = Field(..., description="PKCE code challenge", title="Code Challenge")
    code_challenge_method: CodeChallengeMethod | None = Field(
        "S256", title="Code Challenge Method", validate_default=True
    )
    redirect_uri: str = Field(..., description="Callback URI", title="Redirect Uri")
    scope: str = Field(..., description="Requested scopes", title="Scope")
    state: str = Field(..., description="Client state", title="State")


class AuthorizationResponse(BaseModel):
    code: str = Field(..., description="Authorization code (10 minute expiry)", title="Code")
    state: str = Field(
        ..., description="Client state (echoed back for verification)", title="State"
    )


class AvailableScopesResponse(BaseModel):
    scopes: list[str] = Field(..., title="Scopes")


class BatchDraftRef(BaseModel):
    conversion_id: str = Field(..., title="Conversion Id")
    draft_id: str = Field(..., title="Draft Id")


class BatchVerifyRequest(BaseModel):
    draft_ids: list[BatchDraftRef] = Field(..., max_length=100, min_length=1, title="Draft Ids")


class BodyCompleteSessionApiV1CasesCaseIdSessionsSessionIdCompletePost(BaseModel):
    findings_summary: str = Field(..., title="Findings Summary")


class BodyConvertDocumentApiV1KnowledgeConvertPost(BaseModel):
    file: str = Field(
        ..., json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File"
    )
    scope: str = Field(..., title="Scope")
    team_id: str | None = Field(None, title="Team Id")


class BodyShareCaseWithTeamApiV1CasesCaseIdTeamSharesPost(BaseModel):
    team_id: str = Field(..., description="Team ID to share the case with", title="Team Id")


class BodySubmitTurnApiV1CasesCaseIdTurnsPost(BaseModel):
    files: list[str] | None = Field([], title="Files")
    input_type: str | None = Field(None, title="Input Type")
    intent_data: str | None = Field(None, title="Intent Data")
    intent_type: str | None = Field(None, title="Intent Type")
    observed_at: str | None = Field(None, title="Observed At")
    pasted_content: str | None = Field(None, title="Pasted Content")
    query: str | None = Field(None, title="Query")
    source_url: str | None = Field(None, title="Source Url")


class BodyUploadDocumentApiV1KnowledgeDocumentsPost(BaseModel):
    category: str | None = Field(None, title="Category")
    description: str | None = Field(None, title="Description")
    document_type: str = Field(..., title="Document Type")
    file: str = Field(
        ..., json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File"
    )
    source_url: str | None = Field(None, title="Source Url")
    tags: str | None = Field(None, title="Tags")
    title: str = Field(..., title="Title")


class BreakGlassGrant(BaseModel):
    approval_state: str = Field(..., title="Approval State")
    created_at: AwareDatetime = Field(..., title="Created At")
    deployment_mode: str | None = Field(None, title="Deployment Mode")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    grant_id: str = Field(..., title="Grant Id")
    is_live: bool = Field(..., title="Is Live")
    operator_user_id: str = Field(..., title="Operator User Id")
    operator_username: str | None = Field(None, title="Operator Username")
    reason: str = Field(..., title="Reason")
    revoked_at: AwareDatetime | None = Field(None, title="Revoked At")
    revoked_by: str | None = Field(None, title="Revoked By")
    target_case_id: str = Field(..., title="Target Case Id")
    target_organization_id: str = Field(..., title="Target Organization Id")


class BreakGlassGrantListResponse(BaseModel):
    grants: list[BreakGlassGrant] = Field(..., title="Grants")
    has_more: bool = Field(..., title="Has More")
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total_count: int = Field(..., title="Total Count")


class BreakGlassGrantRequest(BaseModel):
    case_id: constr(min_length=1, max_length=36) = Field(
        ..., description="The single case this grant covers", title="Case Id"
    )
    organization_id: constr(min_length=1, max_length=36) = Field(
        ...,
        description="Organization owning the case; the RLS scope the read rebinds to",
        title="Organization Id",
    )
    reason: constr(min_length=20, max_length=2000) = Field(
        ...,
        description="Why this content must be read. Recorded on every access taken.",
        title="Reason",
    )
    ttl_minutes: conint(ge=1, le=240) | None = Field(
        60,
        description="How long the grant stays live. Cannot be extended later.",
        title="Ttl Minutes",
    )


class CaseCreateRequest(BaseModel):
    description: constr(max_length=2000) | None = Field(
        "", description="Initial problem description", title="Description"
    )
    initial_message: constr(max_length=4000) | None = Field(
        None, description="First user message (for INQUIRY phase)", title="Initial Message"
    )
    session_id: str | None = Field(
        None,
        description="Session ID for authentication and case association (restored from old implementation)",
        title="Session Id",
    )
    title: constr(max_length=200) | None = Field(
        None, description="Case title (optional, auto-generated if not provided)", title="Title"
    )


class CaseState(Enum):
    inquiry = "inquiry"
    investigating = "investigating"
    resolved = "resolved"
    closed = "closed"


class State(Enum):
    resolved = "resolved"
    closed = "closed"


class CaseUpdateRequest(BaseModel):
    description: constr(max_length=2000) | None = Field(
        None, description="Updated description", title="Description"
    )
    state: CaseState | None = Field(None, description="Updated state (admin only)")
    title: constr(max_length=200) | None = Field(None, description="Updated title", title="Title")


class DerivedEvidenceSummary(BaseModel):
    category: str = Field(
        ...,
        description="SYMPTOM_EVIDENCE | CAUSAL_EVIDENCE | SYMPTOM_ABSENCE_EVIDENCE | CAUSAL_ABSENCE_EVIDENCE | OTHER",
        title="Category",
    )
    collected_at_turn: int = Field(..., title="Collected At Turn")
    evidence_id: str = Field(..., title="Evidence Id")
    primary_purpose: str | None = Field(None, title="Primary Purpose")
    related_hypothesis_ids: list[str] | None = Field(None, title="Related Hypothesis Ids")
    source_type: str = Field(
        ..., description="LOGS | METRICS | CONFIGURATION | CODE | TEXT | IMAGE", title="Source Type"
    )
    summary: constr(max_length=500) = Field(..., title="Summary")


class DevLoginRequest(BaseModel):
    display_name: constr(max_length=100) | None = Field(
        None,
        description="Optional display name (will auto-generate if not provided)",
        title="Display Name",
    )
    email: str | None = Field(
        None,
        description="Optional email address (will auto-generate if not provided)",
        title="Email",
    )
    username: constr(min_length=3, max_length=50) = Field(
        ..., description="Username or email address (3-50 chars)", title="Username"
    )


class VerificationStatus(Enum):
    verified = "verified"
    community = "community"
    experimental = "experimental"


class DocumentSnippetResponse(BaseModel):
    document_id: str = Field(..., title="Document Id")
    document_type: str = Field(..., title="Document Type")
    line_range: tuple[int, int] | None = Field(None, title="Line Range")
    relevance_score: float | None = Field(None, title="Relevance Score")
    snippet: str = Field(..., title="Snippet")
    title: str = Field(..., title="Title")
    total_lines: int = Field(..., title="Total Lines")
    verification_level: int | None = Field(0, title="Verification Level")
    verification_status: VerificationStatus | None = Field(
        "experimental", title="Verification Status"
    )


class DraftUpdateRequest(BaseModel):
    content: constr(min_length=100) = Field(
        ..., description="Full runbook markdown content including frontmatter", title="Content"
    )


class EvidenceSummary(BaseModel):
    category: constr(max_length=50) | None = Field(
        "OTHER",
        description="Evidence purpose: SYMPTOM_EVIDENCE | CAUSAL_EVIDENCE | SYMPTOM_ABSENCE_EVIDENCE | CAUSAL_ABSENCE_EVIDENCE | OTHER",
        title="Category",
    )
    collected_at_turn: conint(ge=0) | None = Field(
        0, description="Turn number when evidence was collected", title="Collected At Turn"
    )
    evidence_id: str = Field(..., description="Evidence identifier", title="Evidence Id")
    relevance_score: confloat(ge=0.0, le=1.0) = Field(
        ..., description="Relevance to current investigation (0.0-1.0)", title="Relevance Score"
    )
    source_filename: constr(max_length=255) | None = Field(
        None,
        description="Original filename of the source file, if evidence originated from an attachment.",
        title="Source Filename",
    )
    summary: constr(max_length=500) = Field(
        ..., description="Brief summary of evidence content", title="Summary"
    )
    timestamp: AwareDatetime = Field(
        ..., description="When evidence was collected", title="Timestamp"
    )
    type: constr(max_length=100) = Field(
        ..., description="Evidence type: log_file | metrics_data | config_file | etc.", title="Type"
    )


class FeatureStatus(BaseModel):
    config_hint: str | None = Field(
        "", description="What the user needs to set to enable this feature", title="Config Hint"
    )
    description: str | None = Field(
        "", description="Brief explanation of the feature", title="Description"
    )
    enabled: bool = Field(..., description="Feature is active and usable", title="Enabled")
    has_api_key: bool | None = Field(
        False, description="Required API key is configured", title="Has Api Key"
    )


class HypothesisState(Enum):
    captured = "captured"
    active = "active"
    validated = "validated"
    refuted = "refuted"
    inconclusive = "inconclusive"
    retired = "retired"


class HypothesisSummary(BaseModel):
    evidence_count: conint(ge=0) = Field(
        ...,
        description="Number of evidence items related to this hypothesis",
        title="Evidence Count",
    )
    hypothesis_id: str = Field(..., description="Hypothesis identifier", title="Hypothesis Id")
    likelihood: confloat(ge=0.0, le=1.0) = Field(
        ..., description="Likelihood score (0.0-1.0)", title="Likelihood"
    )
    refutation_reason: constr(max_length=200) | None = Field(
        None,
        description="Reason the hypothesis was refuted. Populated only when status=REFUTED; None otherwise. Mirrors the domain model's pair-integrity invariant.",
        title="Refutation Reason",
    )
    state: HypothesisState = Field(
        ..., description="Status: CAPTURED | ACTIVE | VALIDATED | REFUTED | INCONCLUSIVE | RETIRED"
    )
    text: constr(max_length=500) = Field(..., description="Hypothesis statement", title="Text")


class ImpactData(BaseModel):
    affected_regions: list[str] | None = Field(
        None, description="List of affected geographical regions", title="Affected Regions"
    )
    affected_services: list[str] | None = Field(
        None, description="List of affected services", title="Affected Services"
    )
    affected_users: constr(max_length=500) | None = Field(
        None,
        description="User impact description (e.g., 'All users in US region')",
        title="Affected Users",
    )


class InquiryResponseData(BaseModel):
    decided_to_investigate: bool | None = Field(
        False,
        description="Whether agent has enough info to start investigation",
        title="Decided To Investigate",
    )
    inquiry_turns: conint(ge=0) | None = Field(
        0, description="Number of conversation turns during inquiry phase", title="Inquiry Turns"
    )
    problem_confirmation: dict[str, Any] | None = Field(
        None, description="Problem type and severity guess", title="Problem Confirmation"
    )
    problem_statement_confirmed: bool | None = Field(
        False,
        description="Whether user confirmed the problem statement",
        title="Problem Statement Confirmed",
    )
    proposed_problem_statement: constr(max_length=1000) | None = Field(
        None,
        description="Agent's formalized problem statement (if ready)",
        title="Proposed Problem Statement",
    )


class InvestigationStage(Enum):
    diagnosis = "diagnosis"
    mitigation = "mitigation"
    treatment = "treatment"


class KnowledgeBaseDocument(BaseModel):
    category: str | None = Field(None, title="Category")
    content: str = Field(..., title="Content")
    created_at: str = Field(..., title="Created At")
    document_id: str = Field(..., title="Document Id")
    document_type: str = Field(..., title="Document Type")
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    owner_id: str | None = Field(None, title="Owner Id")
    scope: str | None = Field("global", title="Scope")
    source_suggestion_id: str | None = Field(None, title="Source Suggestion Id")
    source_url: str | None = Field(None, title="Source Url")
    status: str | None = Field("processed", title="Status")
    tags: list[str] | None = Field(None, title="Tags")
    title: str = Field(..., title="Title")
    updated_at: str = Field(..., title="Updated At")
    verification_level: int | None = Field(0, title="Verification Level")
    verification_reason: str | None = Field(None, title="Verification Reason")
    verification_status: VerificationStatus | None = Field(
        "experimental", title="Verification Status"
    )


class LLMConfigUpdateRequest(BaseModel):
    api_key: str | None = Field(
        None, description="New API key value for the specified provider", title="Api Key"
    )
    fallback_chain: list[str] | None = Field(
        None, description="New fallback chain order", title="Fallback Chain"
    )
    model: str | None = Field(
        None,
        description="Model to use for the specified provider (requires provider_name)",
        title="Model",
    )
    primary_provider: str | None = Field(
        None, description="New primary provider name", title="Primary Provider"
    )
    provider_name: str | None = Field(
        None, description="Provider to update API key or model for", title="Provider Name"
    )


class LLMConfigUpdateResponse(BaseModel):
    message: str = Field(..., title="Message")
    timestamp: AwareDatetime = Field(..., title="Timestamp")
    updated_keys: list[str] = Field(
        ..., description="Config keys that were updated", title="Updated Keys"
    )


class LLMConnectionTestRequest(BaseModel):
    provider: str = Field(
        ..., description="Provider name to test (e.g. 'anthropic', 'openai')", title="Provider"
    )


class LLMConnectionTestResponse(BaseModel):
    connected: bool = Field(..., title="Connected")
    error_message: str | None = Field(None, title="Error Message")
    model_used: str | None = Field(None, title="Model Used")
    provider: str = Field(..., title="Provider")
    response_time_ms: int | None = Field(0, title="Response Time Ms")
    timestamp: AwareDatetime = Field(..., title="Timestamp")


class LLMProviderDetail(BaseModel):
    available_models: list[str] | None = Field(
        None,
        description="Models the user can choose from for this provider",
        title="Available Models",
    )
    avg_latency_ms: float | None = Field(0.0, title="Avg Latency Ms")
    connected: bool = Field(
        ..., description="Provider responded to last health check", title="Connected"
    )
    display_name: str = Field(..., title="Display Name")
    enabled: bool = Field(
        ..., description="Provider is initialized and in the fallback chain", title="Enabled"
    )
    error_message: str | None = Field(None, title="Error Message")
    has_api_key: bool = Field(
        ..., description="API key is configured (value never exposed)", title="Has Api Key"
    )
    health: str | None = Field(
        "unknown", description="HEALTHY, DEGRADED, UNHEALTHY, or UNKNOWN", title="Health"
    )
    models: list[str] | None = Field(None, title="Models")
    name: str = Field(..., title="Name")
    selected_model: str | None = Field(
        None, description="Currently active model for this provider", title="Selected Model"
    )
    state: str | None = Field(
        "not_configured",
        description="Provider lifecycle state: not_configured, configured, or active",
        title="State",
    )


class LinkCaseRequest(BaseModel):
    closure_note: constr(max_length=500) | None = Field(None, title="Closure Note")


class LinkCaseResponse(BaseModel):
    case_id: str = Field(..., title="Case Id")
    linked_at: str = Field(..., title="Linked At")
    message: str = Field(..., title="Message")
    report_id: str = Field(..., title="Report Id")
    status: str = Field(..., title="Status")


class LogoutResponse(BaseModel):
    all_sessions_ended: bool | None = Field(
        False,
        description="Whether every session for this account was ended, not just this one. A deliberate sign-out is account-scoped: the dashboard and the browser extension hold independent token chains, so ending only the presented one leaves the other signed in as the previous user. False means the account-wide revocation did not take and other clients may still be active — the caller should say so rather than report a clean sign-out.",
        title="All Sessions Ended",
    )
    message: str | None = Field(
        "Logged out successfully", description="Logout confirmation message", title="Message"
    )
    revoked_tokens: int = Field(
        ...,
        description="Number of tokens revoked by identifier (the presented one)",
        title="Revoked Tokens",
    )


class Role(Enum):
    user = "user"
    assistant = "assistant"
    system = "system"


class Message(BaseModel):
    author_id: str | None = Field(
        None, description="User who created the message", title="Author Id"
    )
    content: str = Field(..., title="Content")
    created_at: str = Field(
        ..., description="ISO 8601 datetime string (matches SQL schema)", title="Created At"
    )
    message_id: str = Field(..., title="Message Id")
    metadata: dict[str, Any] | None = Field(
        None, description="Sources, tools used, etc.", title="Metadata"
    )
    role: Role = Field(..., title="Role")
    token_count: int | None = Field(
        None, description="Number of tokens in content", title="Token Count"
    )
    turn_number: int = Field(
        ...,
        description="Turn number in conversation (user messages increment turn)",
        title="Turn Number",
    )


class MessageRetrievalDebugInfo(BaseModel):
    message_parsing_errors: int | None = Field(
        0, description="Number of messages that failed to parse", title="Message Parsing Errors"
    )
    redis_key: str = Field(..., description="Redis key used for message storage", title="Redis Key")
    redis_operation_time_ms: float = Field(
        ..., description="Time taken for Redis operation", title="Redis Operation Time Ms"
    )
    storage_errors: list[str] | None = Field(
        None, description="Any storage-related errors encountered", title="Storage Errors"
    )


class OAuthConfigResponse(BaseModel):
    authorize_url: str = Field(..., title="Authorize Url")
    client_id: str = Field(..., title="Client Id")
    hosted_login_url: str | None = Field(None, title="Hosted Login Url")
    scopes: list[str] = Field(..., title="Scopes")
    token_url: str = Field(..., title="Token Url")


class OperatorAccessAuditEntry(BaseModel):
    action: str = Field(..., title="Action")
    audit_id: int = Field(..., title="Audit Id")
    created_at: AwareDatetime = Field(..., title="Created At")
    deployment_mode: str | None = Field(None, title="Deployment Mode")
    details: dict[str, Any] | None = Field(None, title="Details")
    expires_at: AwareDatetime | None = Field(None, title="Expires At")
    grant_id: str | None = Field(None, title="Grant Id")
    operator_user_id: str | None = Field(None, title="Operator User Id")
    operator_username: str | None = Field(None, title="Operator Username")
    reason: str | None = Field(None, title="Reason")
    target_case_id: str | None = Field(None, title="Target Case Id")
    target_organization_id: str | None = Field(None, title="Target Organization Id")


class OperatorAccessAuditListResponse(BaseModel):
    entries: list[OperatorAccessAuditEntry] = Field(..., title="Entries")
    has_more: bool = Field(..., title="Has More")
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total_count: int = Field(..., title="Total Count")


class OperatorAction(Enum):
    list = "list"
    content_open = "content_open"
    role_granted = "role_granted"
    role_revoked = "role_revoked"


class OrganizationSummary(BaseModel):
    name: str = Field(..., description="Human-readable organization name", title="Name")
    organization_id: str = Field(
        ..., description="Organization identifier", title="Organization Id"
    )


class ProgressTransparencyInfo(BaseModel):
    active: bool = Field(
        ..., description="Whether transparent mode is active this turn", title="Active"
    )
    cause_assurance: str | None = Field(
        None,
        description="Engine-derived assurance grade behind the identified cause (no_root | mechanistic | confirmed). Lets the frontend label a lower-assurance conclusion — e.g. an identified-but-unconfirmed cause — instead of presenting every conclusion at equal certainty.",
        title="Cause Assurance",
    )
    milestone_description: str | None = Field(
        None,
        description="Human-readable description of what the pending milestone requires",
        title="Milestone Description",
    )
    pending_milestone: str | None = Field(
        None,
        description="Milestone that progress is stalled on (e.g., 'root_cause_identified')",
        title="Pending Milestone",
    )
    repair_type: str | None = Field(
        None,
        description="Agent state repair pattern detected, if any: hypothesis_anchoring, hypothesis_deadlock, exhausted, fix_failure_cycle, action_loop",
        title="Repair Type",
    )
    verification_status: str | None = Field(
        None,
        description="Engine-derived verification status this turn — the grounding × progress join (healthy | treatment_blocked | open | not_yet_productive | insufficient_evidence). Lets the frontend show the honest partial outcome (e.g. insufficient_evidence) alongside the stalled-milestone surfacing.",
        title="Verification Status",
    )


class RelatedHypothesis(BaseModel):
    hypothesis_id: str = Field(..., title="Hypothesis Id")
    stance: str = Field(..., description="SUPPORTS | REFUTES | NEUTRAL", title="Stance")
    statement: str = Field(..., title="Statement")


class ReportAvailability(BaseModel):
    reason: constr(max_length=500) | None = Field(
        None, description="Reason for status (e.g., why recommended)", title="Reason"
    )
    report_type: constr(max_length=100) = Field(
        ..., description="Type: resolution_summary | closure_summary | runbook", title="Report Type"
    )
    status: constr(max_length=50) = Field(
        ...,
        description="Status: available | recommended | in_progress | not_applicable",
        title="Status",
    )


class ReportResponse(BaseModel):
    case_id: str = Field(..., title="Case Id")
    content: str = Field(..., title="Content")
    format: str = Field(..., title="Format")
    generated_at: str = Field(..., title="Generated At")
    generation_status: str = Field(..., title="Generation Status")
    generation_time_ms: int = Field(..., title="Generation Time Ms")
    is_current: bool = Field(..., title="Is Current")
    linked_to_closure: bool = Field(..., title="Linked To Closure")
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    report_id: str = Field(..., title="Report Id")
    report_type: str = Field(..., title="Report Type")
    title: str = Field(..., title="Title")
    version: int = Field(..., title="Version")


class ReportStatus(Enum):
    generating = "generating"
    completed = "completed"
    failed = "failed"


class ReportType(Enum):
    resolution_summary = "resolution_summary"
    closure_summary = "closure_summary"
    runbook = "runbook"


class ReportUpdateRequest(BaseModel):
    content: str | None = Field(
        None, description="Updated report content in markdown", title="Content"
    )
    title: constr(min_length=10, max_length=200) | None = Field(None, title="Title")


class ReportVersionResponse(BaseModel):
    generated_at: str = Field(..., title="Generated At")
    is_current: bool = Field(..., title="Is Current")
    linked_to_closure: bool = Field(..., title="Linked To Closure")
    report_id: str = Field(..., title="Report Id")
    title: str = Field(..., title="Title")
    version: int = Field(..., title="Version")


class ResolutionSummary(BaseModel):
    evidence_collected: conint(ge=0) = Field(
        ..., description="Total evidence items collected", title="Evidence Collected"
    )
    hypotheses_tested: conint(ge=0) = Field(
        ..., description="Number of hypotheses tested", title="Hypotheses Tested"
    )
    key_insights: list[str] | None = Field(
        None, description="Key learnings from this investigation", title="Key Insights"
    )
    milestones_completed: conint(ge=0) = Field(
        ...,
        description="Count of milestones completed over the case's life. A raw count, not a fraction: milestones complete opportunistically and a case can resolve without traversing the mitigation path, so there is no fixed total to compare against.",
        title="Milestones Completed",
    )
    total_duration_minutes: conint(ge=0) = Field(
        ...,
        description="Total time from case creation to resolution",
        title="Total Duration Minutes",
    )


class TokenTypeHint(Enum):
    access_token = "access_token"
    refresh_token = "refresh_token"


class RevokeRequest(BaseModel):
    client_id: str = Field(..., description="OAuth client ID", title="Client Id")
    token: str = Field(..., description="Token to revoke (access or refresh)", title="Token")
    token_type_hint: TokenTypeHint | None = Field(
        None, description="Hint about token type (optional)", title="Token Type Hint"
    )


class RevokeUserTokensResponse(BaseModel):
    message: str = Field(..., description="Revocation confirmation message", title="Message")
    revoked_before: str = Field(
        ...,
        description="Revocation watermark (ISO 8601). Every token for this user issued at or before this instant is now invalid.",
        title="Revoked Before",
    )


class RoleAssignmentRequest(BaseModel):
    role: constr(pattern=r"^(admin|member|viewer)$") = Field(
        ..., description="Role to assign (admin, member, or viewer)", title="Role"
    )


class RoleAssignmentResponse(BaseModel):
    message: str = Field(..., title="Message")
    roles: list[str] = Field(..., title="Roles")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")


class RootCauseSummary(BaseModel):
    category: constr(max_length=100) = Field(
        ...,
        description="Category: code | config | environment | network | data | hardware | external | human | other",
        title="Category",
    )
    cause_assurance: constr(max_length=50) = Field(
        ...,
        description="Engine-derived assurance grade behind this cause (no_root | mechanistic | confirmed), recomputed from the causal graph. The read-time label #572/INV-28 requires beside the cause text: only 'confirmed' is counterfactually verified; 'mechanistic' is identified but unconfirmed; 'no_root' was stated by the assistant without graph validation.",
        title="Cause Assurance",
    )
    cause_overclaim: bool | None = Field(
        False,
        description="True when the conclusion claims 'verified' certainty while the assurance grade is below 'confirmed' (conclusion_overclaims seam). The frontend should surface a caution affordance when set.",
        title="Cause Overclaim",
    )
    description: constr(max_length=1000) = Field(
        ..., description="What caused the problem", title="Description"
    )
    root_cause_id: str = Field(..., description="Root cause identifier", title="Root Cause Id")
    severity: constr(max_length=50) = Field(
        ..., description="Severity: critical | high | medium | low", title="Severity"
    )


class RunbookCreateRequest(BaseModel):
    applicability: constr(min_length=10) = Field(..., title="Applicability")
    causes: constr(min_length=10) = Field(
        ...,
        description="Pre-formatted markdown with ### Cause N subsections (one ROOT each). Each cause needs Statement, an optional Chain (root->D rungs), Indicators (per-rung, [Step N]-anchored), and quadrant-tagged Interventions (remediation/defensive_fix/mitigation/loop_break). Include ### Cause Z: Unidentified with a [Default] indicator as fallback.",
        title="Causes",
    )
    diagnostic_steps: constr(min_length=10) = Field(..., title="Diagnostic Steps")
    difficulty: str | None = Field("intermediate", title="Difficulty")
    domain: str = Field(..., title="Domain")
    prevention: constr(min_length=10) = Field(..., title="Prevention")
    scope: str = Field(..., title="Scope")
    service: str = Field(..., title="Service")
    severity: str = Field(..., title="Severity")
    symptom_class: list[str] = Field(..., min_length=1, title="Symptom Class")
    symptom_recognition: constr(min_length=10) = Field(..., title="Symptom Recognition")
    tags: list[str] | None = Field(None, title="Tags")
    team_id: str | None = Field(None, title="Team Id")
    title: constr(min_length=10, max_length=100) = Field(..., title="Title")


class RunbookSource(Enum):
    incident_driven = "incident_driven"
    document_driven = "document_driven"


class SSOExchangeRequest(BaseModel):
    code: constr(min_length=16, max_length=128) = Field(..., title="Code")


class SearchRequest(BaseModel):
    category: str | None = Field(None, description="Filter by document category", title="Category")
    document_type: str | None = Field(
        None, description="Filter by document type", title="Document Type"
    )
    filters: dict[str, Any] | None = Field(
        None, description="Advanced filters for search", title="Filters"
    )
    limit: conint(le=100, gt=0) | None = Field(
        10, description="Maximum number of results", title="Limit"
    )
    query: constr(min_length=1) = Field(..., description="Search query", title="Query")
    rank_by: str | None = Field(
        None, description="Field to rank results by (e.g., priority)", title="Rank By"
    )
    similarity_threshold: confloat(ge=0.0, le=1.0) | None = Field(
        None,
        description="Minimum similarity score threshold (0.0-1.0)",
        title="Similarity Threshold",
    )
    tags: str | None = Field(None, description="Filter by tags (comma-separated)", title="Tags")


class SessionCreateRequest(BaseModel):
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    session_goal: str | None = Field(None, title="Session Goal")
    token_budget_limit: conint(ge=0) | None = Field(None, title="Token Budget Limit")


class SessionResponse(BaseModel):
    client_id: str | None = Field(None, title="Client Id")
    created_at: str = Field(..., title="Created At")
    expires_at: str | None = Field(None, title="Expires At")
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    schema_version: Literal["3.1.0"] = Field("3.1.0", title="Schema Version")
    session_id: str = Field(..., title="Session Id")
    session_resumed: bool | None = Field(None, title="Session Resumed")
    status: AuthSessionStatus | None = "active"
    user_id: str | None = Field(None, title="User Id")


class SessionRestoreRequest(BaseModel):
    include_data: bool | None = Field(True, title="Include Data")
    restore_point: constr(min_length=1) = Field(..., title="Restore Point")
    type: str | None = Field("full", title="Type")


class SessionState(Enum):
    active = "active"
    paused = "paused"
    completed = "completed"
    abandoned = "abandoned"


class SessionUpdateRequest(BaseModel):
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    session_goal: str | None = Field(None, title="Session Goal")
    token_budget_limit: conint(ge=0) | None = Field(None, title="Token Budget Limit")


class SolutionSummary(BaseModel):
    applied_at: AwareDatetime = Field(
        ..., description="When solution was applied", title="Applied At"
    )
    applied_by: str = Field(
        ..., description="Who applied the solution (user_id or 'agent')", title="Applied By"
    )
    description: constr(max_length=2000) = Field(
        ..., description="What was done to fix the problem", title="Description"
    )


class SolutionVerificationData(BaseModel):
    details: constr(max_length=1000) = Field(
        ..., description="Verification details and metrics", title="Details"
    )
    verification_method: constr(max_length=500) = Field(
        ..., description="How verification was done", title="Verification Method"
    )
    verified: bool = Field(
        ..., description="Whether solution effectiveness was verified", title="Verified"
    )


class SourceFileReference(BaseModel):
    file_id: str = Field(..., title="File Id")
    filename: str = Field(..., title="Filename")
    uploaded_at_turn: int = Field(..., title="Uploaded At Turn")


class SuggestedActionResponse(BaseModel):
    body: str | None = Field(None, title="Body")
    evidence_need_id: str | None = Field(None, title="Evidence Need Id")
    hints: list[str] | None = Field(None, title="Hints")
    intent: dict[str, Any] | None = Field(None, title="Intent")
    label: str = Field(..., title="Label")
    payload: str | None = Field(None, title="Payload")
    type: str = Field(..., title="Type")


class TeamResponse(BaseModel):
    description: str | None = Field(None, title="Description")
    name: str = Field(..., title="Name")
    organization_id: str = Field(..., title="Organization Id")
    team_id: str = Field(..., title="Team Id")


class TemporalStateData(BaseModel):
    last_occurrence_at: AwareDatetime | None = Field(
        None, description="Most recent occurrence of the problem", title="Last Occurrence At"
    )
    started_at: AwareDatetime | None = Field(
        None, description="When the problem started", title="Started At"
    )
    state: constr(max_length=50) | None = Field(
        None, description="Temporal state: ongoing | historical | intermittent", title="State"
    )


class TitleResponse(BaseModel):
    schema_version: str | None = Field("3.1.0", title="Schema Version")
    title: str = Field(..., title="Title")


class TokenRefreshRequest(BaseModel):
    refresh_token: str = Field(
        ...,
        description="The refresh token issued at login or a prior refresh",
        title="Refresh Token",
    )


class TokenRefreshResponse(BaseModel):
    access_token: str = Field(..., description="New bearer access token", title="Access Token")
    expires_in: int = Field(..., description="Token expiration time in seconds", title="Expires In")
    refresh_token: str = Field(
        ...,
        description="New refresh token (the old one is revoked — rotation)",
        title="Refresh Token",
    )
    token_type: str | None = Field(
        "bearer", description="Token type (always 'bearer')", title="Token Type"
    )


class GrantType(Enum):
    authorization_code = "authorization_code"
    refresh_token = "refresh_token"


class TokenRequest(BaseModel):
    client_id: str = Field(..., description="OAuth client ID", title="Client Id")
    code: str | None = Field(
        None, description="Authorization code (required for authorization_code grant)", title="Code"
    )
    code_verifier: str | None = Field(
        None,
        description="PKCE code verifier (required for authorization_code grant)",
        title="Code Verifier",
    )
    grant_type: GrantType = Field(
        ..., description="Grant type: 'authorization_code' or 'refresh_token'", title="Grant Type"
    )
    redirect_uri: str | None = Field(
        None,
        description="Redirect URI (required for authorization_code grant, must match)",
        title="Redirect Uri",
    )
    refresh_token: str | None = Field(
        None, description="Refresh token (required for refresh_token grant)", title="Refresh Token"
    )


class TokenResponse(BaseModel):
    access_token: str = Field(
        ..., description="JWT access token (15 minute expiry)", title="Access Token"
    )
    expires_in: int = Field(
        ..., description="Access token expiry in seconds (900)", title="Expires In"
    )
    refresh_expires_in: int = Field(
        ..., description="Refresh token expiry in seconds (604800)", title="Refresh Expires In"
    )
    refresh_token: str = Field(
        ..., description="JWT refresh token (7 days expiry)", title="Refresh Token"
    )
    token_type: str | None = Field(
        "Bearer", description="Token type (always Bearer)", title="Token Type"
    )
    user_id: str = Field(..., description="User ID", title="User Id")
    username: str = Field(..., description="Username", title="Username")


class TurnResponse(BaseModel):
    agent_response: str = Field(..., title="Agent Response")
    attachments_processed: list[AttachmentResult] | None = Field(
        None, title="Attachments Processed"
    )
    case_state: CaseState
    cause_assurance: str | None = Field(
        None,
        description="Engine-derived assurance grade behind the case's identified cause (no_root | mechanistic | confirmed), recomputed from the causal graph. Present whenever the case has stated a root cause. Lets a narration-only client (e.g. Slack) show the #572/INV-28 read-time label beside the cause claim carried in agent_response, rather than presenting every conclusion at equal certainty.",
        title="Cause Assurance",
    )
    cause_overclaim: bool | None = Field(
        None,
        description="True when the case's conclusion claims 'verified' certainty while the assurance grade is below 'confirmed' (conclusion_overclaims seam). None when no cause is stated.",
        title="Cause Overclaim",
    )
    milestones_completed: list[str] = Field(..., title="Milestones Completed")
    progress_made: bool = Field(..., title="Progress Made")
    progress_transparency: ProgressTransparencyInfo | None = Field(
        None,
        description="Progress transparency state. Present when investigation has stalled and agent is surfacing milestone dependencies.",
    )
    suggested_actions: list[SuggestedActionResponse] | None = Field(None, title="Suggested Actions")
    turn_number: int = Field(..., title="Turn Number")


class UploadedFileDetailsResponse(BaseModel):
    content_hash: str | None = Field(
        None, description="SHA-256 of file contents (storage-backend dedup)", title="Content Hash"
    )
    content_type: str | None = Field(
        None, description="MIME type as reported on upload", title="Content Type"
    )
    derived_evidence: list[DerivedEvidenceSummary] | None = Field(None, title="Derived Evidence")
    evidence_count: conint(ge=0) = Field(..., title="Evidence Count")
    file_id: str = Field(..., title="File Id")
    filename: str = Field(..., title="Filename")
    size_bytes: int = Field(..., title="Size Bytes")
    size_display: str = Field(..., title="Size Display")
    summary: str | None = Field(
        None,
        description="File-level preprocessing summary, set by the ingestion pipeline.",
        title="Summary",
    )
    upload_source: str = Field(
        ...,
        description="Provenance: file_upload | paste | screenshot | page_capture | agent_generated | conversion_source",
        title="Upload Source",
    )
    uploaded_at: AwareDatetime = Field(..., title="Uploaded At")
    uploaded_at_turn: int = Field(..., title="Uploaded At Turn")


class UploadedFileMetadata(BaseModel):
    analysis_status: str = Field(
        ..., description="pending | processing | completed | failed", title="Analysis Status"
    )
    file_id: str = Field(..., description="Evidence/File identifier", title="File Id")
    filename: str = Field(..., description="Original or generated filename", title="Filename")
    size_bytes: conint(ge=0) = Field(..., description="File size in bytes", title="Size Bytes")
    size_display: str = Field(
        ..., description="Human-readable size (e.g., '2.3 MB')", title="Size Display"
    )
    source_metadata: dict[str, Any] | None = Field(
        None, description="Source origin metadata (e.g. page capture URL)", title="Source Metadata"
    )
    source_type: str = Field(
        ...,
        description="file_upload | paste | screenshot | page_injection | agent_generated",
        title="Source Type",
    )
    summary: str | None = Field(
        None, description="AI-generated summary (1-2 sentences)", title="Summary"
    )
    uploaded_at: AwareDatetime = Field(..., description="Upload timestamp", title="Uploaded At")
    uploaded_at_turn: conint(ge=0) = Field(
        ..., description="Turn when file was uploaded", title="Uploaded At Turn"
    )


class UploadedFilesList(BaseModel):
    files: list[UploadedFileMetadata] = Field(..., title="Files")
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total_count: int = Field(..., description="Total number of files", title="Total Count")


class UserDetailResponse(BaseModel):
    created_at: AwareDatetime = Field(..., title="Created At")
    email: str = Field(..., title="Email")
    full_name: str = Field(..., title="Full Name")
    is_active: bool = Field(..., title="Is Active")
    is_verified: bool = Field(..., title="Is Verified")
    last_login_at: AwareDatetime | None = Field(None, title="Last Login At")
    metadata: dict[str, Any] | None = Field(None, title="Metadata")
    organization_id: str = Field(..., title="Organization Id")
    permissions: list[str] = Field(..., title="Permissions")
    roles: list[str] = Field(..., title="Roles")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")


class UserInfoResponse(BaseModel):
    created_at: str = Field(
        ..., description="Account creation timestamp (ISO format)", title="Created At"
    )
    display_name: str = Field(..., description="Display name", title="Display Name")
    email: str = Field(..., description="Email address", title="Email")
    is_dev_user: bool | None = Field(True, description="Development user flag", title="Is Dev User")
    last_login: str | None = Field(
        None, description="Last login timestamp (ISO format)", title="Last Login"
    )
    organization: OrganizationSummary | None = Field(
        None,
        description="The organization this session is bound to, or null when there is no usable tenant for this request or its row could not be read. Under multi-tenant this is the tenant a case is written into; under single-tenant it is the deployment's one organization. Absence means 'nothing to show', never 'no access' — the request itself already succeeded, so a client must not read null as a permission signal.",
    )
    roles: list[str] | None = Field(
        ["user"],
        description="User roles for access control (e.g., ['user'], ['user', 'admin'])",
        title="Roles",
    )
    user_id: str = Field(..., description="Unique user identifier", title="User Id")
    username: str = Field(..., description="Username", title="Username")


class UserProfile(BaseModel):
    created_at: str = Field(
        ..., description="Account creation timestamp (ISO format)", title="Created At"
    )
    display_name: str = Field(..., description="Display name", title="Display Name")
    email: str = Field(..., description="Email address", title="Email")
    is_dev_user: bool | None = Field(True, description="Development user flag", title="Is Dev User")
    roles: list[str] | None = Field(
        ["user"],
        description="User roles for access control (e.g., ['user'], ['user', 'admin'])",
        title="Roles",
    )
    user_id: str = Field(..., description="Unique user identifier", title="User Id")
    username: str = Field(..., description="Username", title="Username")


class UserStatusResponse(BaseModel):
    is_active: bool = Field(..., title="Is Active")
    message: str = Field(..., title="Message")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title="Context")
    input: Any | None = Field(None, title="Input")
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class WorkingConclusionSummary(BaseModel):
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ..., description="Confidence level (0.0-1.0)", title="Confidence"
    )
    last_updated: AwareDatetime = Field(
        ..., description="When this conclusion was last updated", title="Last Updated"
    )
    summary: constr(max_length=1000) = Field(
        ..., description="Current best theory about the problem", title="Summary"
    )


class AdminCaseMetadata(BaseModel):
    case_id: str = Field(..., title="Case Id")
    closed_at: AwareDatetime | None = Field(..., title="Closed At")
    closure_reason: str | None = Field(..., title="Closure Reason")
    created_at: AwareDatetime = Field(..., title="Created At")
    current_turn: int = Field(..., title="Current Turn")
    is_terminal: bool = Field(..., title="Is Terminal")
    last_activity_at: AwareDatetime = Field(..., title="Last Activity At")
    organization_id: str = Field(..., title="Organization Id")
    resolved_at: AwareDatetime | None = Field(..., title="Resolved At")
    source: str | None = Field("copilot", title="Source")
    stage: InvestigationStage | None
    state: CaseState
    turns_without_progress: int = Field(..., title="Turns Without Progress")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")


class AdminCaseMetadataListResponse(BaseModel):
    cases: list[AdminCaseMetadata] = Field(..., title="Cases")
    has_more: bool = Field(..., title="Has More")
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total_count: int = Field(..., title="Total Count")
    view: Literal["metadata"] = Field("metadata", title="View")


class AuthConfigResponse(BaseModel):
    auth_mode: str = Field(..., title="Auth Mode")
    login_endpoint: str | None = Field(None, title="Login Endpoint")
    oauth: OAuthConfigResponse | None = None
    register_endpoint: str | None = Field(None, title="Register Endpoint")
    supports_registration: bool = Field(..., title="Supports Registration")


class AuthTokenResponse(BaseModel):
    access_token: str = Field(..., description="Bearer access token", title="Access Token")
    expires_in: int = Field(..., description="Token expiration time in seconds", title="Expires In")
    idp_logout_url: str | None = Field(
        None,
        description="Where to send the browser to end the identity provider's own session. Populated only for SSO logins; null for password and dev logins, which have no IdP session. A client signing a user out must navigate here after clearing local state: revoking FaultMaven's token does not end the IdP session, so omitting it leaves the next sign-in answered silently, the account unswitchable, and a shared browser one click from being signed back in.",
        title="Idp Logout Url",
    )
    refresh_token: str | None = Field(
        None,
        description="Long-lived refresh token used to mint a new access token via POST /auth/refresh without re-authenticating. Issued in local mode; clients should persist it and refresh before the access token expires.",
        title="Refresh Token",
    )
    session_id: str = Field(
        ..., description="Session identifier for multi-turn conversations", title="Session Id"
    )
    token_type: str | None = Field(
        "bearer", description="Token type (always 'bearer')", title="Token Type"
    )
    user: UserProfile = Field(..., description="Authenticated user profile")


class CaseDetail(BaseModel):
    case_id: str = Field(..., title="Case Id")
    closed_at: AwareDatetime | None = Field(..., title="Closed At")
    closure_reason: str | None = Field(..., title="Closure Reason")
    created_at: AwareDatetime = Field(..., title="Created At")
    current_stage: InvestigationStage | None
    current_turn: int = Field(..., title="Current Turn")
    description: str = Field(..., title="Description")
    escalated: bool = Field(..., title="Escalated")
    evidence_count: int = Field(..., title="Evidence Count")
    hypothesis_count: int = Field(..., title="Hypothesis Count")
    is_terminal: bool = Field(..., title="Is Terminal")
    last_activity_at: AwareDatetime = Field(..., title="Last Activity At")
    milestones_completed: list[str] = Field(..., title="Milestones Completed")
    organization_id: str = Field(..., title="Organization Id")
    pending_milestones: list[str] = Field(..., title="Pending Milestones")
    resolved_at: AwareDatetime | None = Field(..., title="Resolved At")
    shared_team_ids: list[str] | None = Field(None, title="Shared Team Ids")
    solution_count: int = Field(..., title="Solution Count")
    source: str | None = Field("copilot", title="Source")
    state: CaseState
    title: str = Field(..., title="Title")
    turns_without_progress: int = Field(..., title="Turns Without Progress")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")
    valid_next_states: list[str] | None = Field(
        None,
        description="Allowed state transitions from current state for user-initiated changes",
        title="Valid Next States",
    )


class CaseMessagesResponse(BaseModel):
    debug_info: MessageRetrievalDebugInfo | None = Field(
        None, description="Debug information (only when include_debug=true)"
    )
    has_more: bool = Field(
        ..., description="Whether more messages are available for pagination", title="Has More"
    )
    messages: list[Message] = Field(
        ..., description="Array of conversation messages", title="Messages"
    )
    next_offset: int | None = Field(
        None, description="Offset for next page (null if no more pages)", title="Next Offset"
    )
    retrieved_count: int = Field(
        ..., description="Number of messages successfully retrieved", title="Retrieved Count"
    )
    total_count: int = Field(
        ..., description="Total number of messages in the case", title="Total Count"
    )


class CaseSearchRequest(BaseModel):
    limit: conint(ge=1, le=100) | None = Field(20, description="Maximum results", title="Limit")
    organization_id: str | None = Field(
        None, description="Limit to organization's cases", title="Organization Id"
    )
    query: constr(min_length=1, max_length=500) = Field(
        ..., description="Search query", title="Query"
    )
    state: CaseState | None = Field(None, description="Filter by state")
    team_id: str | None = Field(
        None,
        description="Filter to cases shared with this Team (ADR-013 §D4). Only Teams the caller belongs to yield results; ignored in standalone (no teams).",
        title="Team Id",
    )
    user_id: str | None = Field(None, description="Limit to user's cases", title="User Id")


class CaseSummary(BaseModel):
    case_id: str = Field(..., title="Case Id")
    closed_at: AwareDatetime | None = Field(..., title="Closed At")
    closure_reason: str | None = Field(..., title="Closure Reason")
    created_at: AwareDatetime = Field(..., title="Created At")
    current_turn: int = Field(..., title="Current Turn")
    description: str = Field(..., title="Description")
    is_terminal: bool = Field(..., title="Is Terminal")
    last_activity_at: AwareDatetime = Field(..., title="Last Activity At")
    organization_id: str = Field(..., title="Organization Id")
    resolved_at: AwareDatetime | None = Field(..., title="Resolved At")
    shared_team_ids: list[str] | None = Field(None, title="Shared Team Ids")
    source: str | None = Field("copilot", title="Source")
    stage: InvestigationStage | None
    state: CaseState
    title: str = Field(..., title="Title")
    turns_without_progress: int = Field(..., title="Turns Without Progress")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")
    valid_next_states: list[str] | None = Field(
        None,
        description="Allowed state transitions from current state for user-initiated changes",
        title="Valid Next States",
    )


class CaseUIResponseInquiry(BaseModel):
    case_id: str = Field(..., description="Case identifier", title="Case Id")
    created_at: AwareDatetime = Field(..., description="When case was created", title="Created At")
    current_turn: conint(ge=0) = Field(
        ..., description="Current turn counter", title="Current Turn"
    )
    disposition_eligibility: dict[str, str] | None = Field(
        None,
        description="Per-disposition eligibility for UI affordance gating. Shape: ``{'resolved': str, 'closed': str}`` where each value is one of:\n- ``ready`` — disposition is appropriate; render the affordance enabled with the default 'click to confirm' UX.\n- ``needs_info`` — disposition is allowed but the case is partial; user must ADD information (root cause / solution) before transitioning. UX: prompt the user for the missing data. Currently only the Resolve side surfaces this.\n- ``suggests_alternative`` — disposition is allowed but the system recommends the OTHER disposition for this case. UX: warn and offer the alternative; if the user confirms anyway, proceed. Distinct from ``needs_info`` — no data is missing; the user is asked to RE-DIRECT, not to add. Currently only the Close side surfaces this (when the case has root cause + solution → resolving preserves attribution).\n- ``not_eligible`` — disposition is not available; hide the affordance entirely.\n\nDifferent from ``valid_next_states`` — that field is the structural action graph (which edges exist), this field is the content-readiness layer on top.",
        title="Disposition Eligibility",
    )
    inquiry: InquiryResponseData = Field(..., description="Nested inquiry phase data")
    state: Literal["inquiry"] = Field(
        "inquiry", description="Always 'inquiry' for this response type", title="State"
    )
    title: constr(max_length=200) = Field(..., description="Case title", title="Title")
    updated_at: AwareDatetime = Field(..., description="Last update timestamp", title="Updated At")
    uploaded_files_count: conint(ge=0) = Field(
        ..., description="Total files uploaded", title="Uploaded Files Count"
    )
    valid_next_states: list[str] | None = Field(
        None,
        description="Allowed state transitions from current state for user-initiated changes",
        title="Valid Next States",
    )


class CaseUIResponseResolved(BaseModel):
    case_id: str = Field(..., description="Case identifier", title="Case Id")
    created_at: AwareDatetime = Field(..., description="When case was created", title="Created At")
    current_turn: conint(ge=0) = Field(
        ..., description="Current turn counter", title="Current Turn"
    )
    disposition_eligibility: dict[str, str] | None = Field(
        None,
        description="Per-disposition eligibility for UI affordance gating. Shape: ``{'resolved': str, 'closed': str}`` where each value is one of:\n- ``ready`` — disposition is appropriate; render the affordance enabled with the default 'click to confirm' UX.\n- ``needs_info`` — disposition is allowed but the case is partial; user must ADD information (root cause / solution) before transitioning. UX: prompt the user for the missing data. Currently only the Resolve side surfaces this.\n- ``suggests_alternative`` — disposition is allowed but the system recommends the OTHER disposition for this case. UX: warn and offer the alternative; if the user confirms anyway, proceed. Distinct from ``needs_info`` — no data is missing; the user is asked to RE-DIRECT, not to add. Currently only the Close side surfaces this (when the case has root cause + solution → resolving preserves attribution).\n- ``not_eligible`` — disposition is not available; hide the affordance entirely.\n\nDifferent from ``valid_next_states`` — that field is the structural action graph (which edges exist), this field is the content-readiness layer on top.",
        title="Disposition Eligibility",
    )
    problem_statement: constr(max_length=1000) | None = Field(
        None,
        description="Confirmed problem statement carried over from INQUIRY (sourced from case.description).",
        title="Problem Statement",
    )
    reports_available: list[ReportAvailability] | None = Field(
        None,
        description="Available reports (incident report, post-mortem, runbook)",
        title="Reports Available",
    )
    resolution_summary: ResolutionSummary = Field(
        ..., description="Overall resolution metrics and insights"
    )
    resolved_at: AwareDatetime = Field(
        ..., description="When case was resolved", title="Resolved At"
    )
    root_cause: RootCauseSummary = Field(..., description="What caused the problem")
    solution_applied: SolutionSummary = Field(..., description="Solution that fixed the problem")
    state: State = Field(
        ...,
        description="Case terminal state: 'resolved' (with solution) or 'closed' (without investigation)",
        title="State",
    )
    title: constr(max_length=200) = Field(..., description="Case title", title="Title")
    updated_at: AwareDatetime = Field(..., description="Last update timestamp", title="Updated At")
    uploaded_files_count: int | None = Field(
        0, description="Number of uploaded files", title="Uploaded Files Count"
    )
    valid_next_states: list[str] | None = Field(
        None,
        description="Allowed state transitions from current state for user-initiated changes",
        title="Valid Next States",
    )
    verification_status: SolutionVerificationData = Field(
        ..., description="How solution effectiveness was verified"
    )


class EnvConfigStatusResponse(BaseModel):
    auth_mode: str = Field(..., description="'local' or 'oauth'", title="Auth Mode")
    db_backend: str = Field(..., description="'sqlite' or 'postgresql'", title="Db Backend")
    deployment: str = Field(
        ...,
        description="'standalone' or 'cloud' — from DEPLOYMENT_MODE (ADR-004)",
        title="Deployment",
    )
    features: dict[str, FeatureStatus] | None = Field(
        None, description="Optional features and their configuration status", title="Features"
    )
    llm_provider: str = Field(..., description="Primary LLM provider name", title="Llm Provider")
    pii_redaction_enabled: bool = Field(..., title="Pii Redaction Enabled")
    rate_limit_enabled: bool = Field(
        ...,
        description="Rate limiting middleware is installed on this deployment. Read from the running middleware stack rather than from configuration: no rate-limit setting exists, the protection presets decide by environment name, and no environment variable turns it off. A deployment reports false here only if protection setup raised and the development carve-out let it boot anyway.",
        title="Rate Limit Enabled",
    )
    session_storage: str = Field(..., description="'inmemory' or 'redis'", title="Session Storage")
    timestamp: AwareDatetime = Field(..., title="Timestamp")
    vector_storage: str = Field(..., description="'inmemory' or 'chromadb'", title="Vector Storage")


class EvidenceDetailsResponse(BaseModel):
    analysis: str | None = Field(None, title="Analysis")
    case_id: str = Field(..., title="Case Id")
    category: str = Field(..., title="Category")
    collected_at: AwareDatetime = Field(..., title="Collected At")
    collected_at_turn: int = Field(..., title="Collected At Turn")
    collected_by: str = Field(..., title="Collected By")
    evidence_id: str = Field(..., title="Evidence Id")
    extract: str | None = Field(
        None,
        description="Optional verbatim quote backing the summary. NULL when the LLM omitted it (the summary is self-contained).",
        title="Extract",
    )
    primary_purpose: str = Field(..., title="Primary Purpose")
    related_hypotheses: list[RelatedHypothesis] | None = Field(None, title="Related Hypotheses")
    source_file: SourceFileReference | None = Field(
        None,
        description="Source file this evidence was derived from. NULL only when the evidence is a verbatim quote extracted from the user's chat message (source_type=USER_DESCRIPTION).",
    )
    summary: constr(max_length=500) = Field(..., title="Summary")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class InvestigationProgressSummary(BaseModel):
    active_hypotheses: conint(ge=0) | None = Field(
        0, description="Number of hypotheses currently being tested", title="Active Hypotheses"
    )
    completed_indicators: list[str] | None = Field(
        None,
        description="Completed progress indicators (e.g. symptom_verified, root_cause_identified)",
        title="Completed Indicators",
    )
    completed_stage_gates: list[str] | None = Field(
        None,
        description="Completed stage-gate milestones (e.g. mitigation_accepted, solution_verified)",
        title="Completed Stage Gates",
    )
    current_stage: InvestigationStage = Field(
        ..., description="Current stage: DIAGNOSIS | MITIGATION | TREATMENT"
    )
    total_evidence: conint(ge=0) | None = Field(
        0, description="Total evidence items collected", title="Total Evidence"
    )
    turns_without_progress: int | None = Field(
        0,
        description="Consecutive turns without milestone, evidence, or hypothesis progress",
        title="Turns Without Progress",
    )


class InvestigationSessionResponse(BaseModel):
    case_id: str = Field(..., title="Case Id")
    created_at: AwareDatetime = Field(..., title="Created At")
    ended_at: AwareDatetime | None = Field(None, title="Ended At")
    findings_summary: str | None = Field(None, title="Findings Summary")
    last_activity_at: AwareDatetime = Field(..., title="Last Activity At")
    organization_id: str = Field(..., title="Organization Id")
    session_goal: str | None = Field(None, title="Session Goal")
    session_id: str = Field(..., title="Session Id")
    started_at: AwareDatetime = Field(..., title="Started At")
    state: SessionState
    token_budget_limit: int | None = Field(None, title="Token Budget Limit")
    total_agent_executions: int = Field(..., title="Total Agent Executions")
    total_duration_ms: int | None = Field(None, title="Total Duration Ms")
    total_token_usage: int = Field(..., title="Total Token Usage")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    user_id: str = Field(..., title="User Id")


class LLMConfigResponse(BaseModel):
    config_readonly: bool = Field(
        ...,
        description="True in standalone mode (config managed via .env file)",
        title="Config Readonly",
    )
    config_sources: dict[str, str] | None = Field(
        None,
        description="Provenance per overridable setting key: 'admin-override' (set via the dashboard, stored in the DB) or 'env-default' (.env / seed). Always 'env-default' in standalone (no DB overrides).",
        title="Config Sources",
    )
    deployment: str = Field(
        ..., description="Deployment mode: 'standalone' or 'cloud'", title="Deployment"
    )
    fallback_chain: list[str] = Field(..., title="Fallback Chain")
    primary_provider: str = Field(..., title="Primary Provider")
    providers: dict[str, LLMProviderDetail] = Field(..., title="Providers")
    strict_mode: bool = Field(..., title="Strict Mode")
    timestamp: AwareDatetime = Field(..., title="Timestamp")


class ProblemVerificationData(BaseModel):
    impact: ImpactData | None = Field(
        None, description="Scope of impact (services, users, regions)"
    )
    severity: constr(max_length=50) | None = Field(
        None, description="Severity: critical | high | medium | low", title="Severity"
    )
    temporal_state: TemporalStateData | None = Field(
        None, description="When the problem occurred and its temporal pattern"
    )
    urgency_level: constr(max_length=50) | None = Field(
        None, description="Urgency: critical | high | medium | low | unknown", title="Urgency Level"
    )
    user_impact: constr(max_length=1000) | None = Field(
        None, description="Human-readable user impact summary", title="User Impact"
    )


class ReportGenerationRequest(BaseModel):
    report_types: list[ReportType] = Field(
        ...,
        description="Types of reports to generate",
        max_length=3,
        min_length=1,
        title="Report Types",
    )


class ReportListResponse(BaseModel):
    case_id: str = Field(..., title="Case Id")
    reports: list[ReportResponse] = Field(..., title="Reports")
    total: int = Field(..., title="Total")


class ReportVersionListResponse(BaseModel):
    total: int = Field(..., title="Total")
    versions: list[ReportVersionResponse] = Field(..., title="Versions")


class RunbookMetadata(BaseModel):
    case_context: dict[str, Any] | None = Field(
        None, description="Case investigation context (incident-driven only)", title="Case Context"
    )
    document_title: str | None = Field(
        None, description="Source document title (document-driven only)", title="Document Title"
    )
    domain: str = Field(..., description="Technology domain for filtering", title="Domain")
    embedding_model: str | None = Field(
        None, description="Embedding model for vector search", title="Embedding Model"
    )
    llm_model: str | None = Field(
        None, description="LLM model used for generation", title="Llm Model"
    )
    original_document_id: str | None = Field(
        None,
        description="Reference to uploaded document (document-driven only)",
        title="Original Document Id",
    )
    source: RunbookSource = Field(..., description="Origin of runbook")
    tags: list[str] | None = Field(None, description="Classification tags", title="Tags")


class AdminCaseContentResponse(BaseModel):
    access: Access = Field(..., title="Access")
    case: CaseDetail
    grant: BreakGlassGrant | None = None


class AdminCaseListResponse(BaseModel):
    cases: list[CaseSummary] = Field(..., title="Cases")
    has_more: bool = Field(..., title="Has More")
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total_count: int = Field(..., title="Total Count")
    view: Literal["full"] = Field("full", title="View")


class AdminCaseMessagesResponse(BaseModel):
    access: Access = Field(..., title="Access")
    grant: BreakGlassGrant | None = None
    messages: CaseMessagesResponse


class CaseEvidenceListResponse(BaseModel):
    case_id: str = Field(..., title="Case Id")
    evidence: list[EvidenceDetailsResponse] = Field(..., title="Evidence")
    total_count: int = Field(..., title="Total Count")


class CaseListResponse(BaseModel):
    cases: list[CaseSummary] = Field(..., title="Cases")
    has_more: bool = Field(..., title="Has More")
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    total_count: int = Field(..., title="Total Count")


class CaseReport(BaseModel):
    auto_generated: bool | None = Field(
        False,
        description="True for auto-generated terminal summaries, False for user-requested reports",
        title="Auto Generated",
    )
    case_id: str = Field(
        ...,
        description="Foreign key to parent case (or 'doc-derived' for document-driven)",
        title="Case Id",
    )
    content: str = Field(..., description="Full report content in Markdown format", title="Content")
    format: Literal["markdown"] = Field("markdown", description="Report format", title="Format")
    generated_at: str | None = Field(
        None, description="ISO 8601 timestamp when report was first generated", title="Generated At"
    )
    generation_status: ReportStatus = Field(..., description="Generation status")
    generation_time_ms: conint(ge=0, le=120000) = Field(
        ..., description="Generation time (ms)", title="Generation Time Ms"
    )
    is_current: bool | None = Field(
        True, description="Latest version for this report_type", title="Is Current"
    )
    linked_to_closure: bool | None = Field(
        False, description="Linked to case closure", title="Linked To Closure"
    )
    metadata: RunbookMetadata | None = Field(None, description="Runbook-specific metadata")
    report_id: str | None = Field(
        None, description="Unique report identifier (UUID v4)", title="Report Id"
    )
    report_type: ReportType = Field(..., description="Type of report")
    title: constr(min_length=10, max_length=200) = Field(
        ..., description="Human-readable title", title="Title"
    )
    updated_at: str | None = Field(
        None,
        description="ISO 8601 timestamp when report was last updated (None for new reports, set on update)",
        title="Updated At",
    )
    version: conint(ge=1, le=5) | None = Field(1, description="Version number", title="Version")


class CaseUIResponseInvestigating(BaseModel):
    active_hypotheses: list[HypothesisSummary] | None = Field(
        None, description="Hypotheses currently being tested", title="Active Hypotheses"
    )
    agent_status: constr(max_length=500) = Field(
        ..., description="What agent is currently doing", title="Agent Status"
    )
    case_id: str = Field(..., description="Case identifier", title="Case Id")
    created_at: AwareDatetime = Field(..., description="When case was created", title="Created At")
    current_turn: conint(ge=0) = Field(
        ..., description="Current turn counter", title="Current Turn"
    )
    disposition_eligibility: dict[str, str] | None = Field(
        None,
        description="Per-disposition eligibility for UI affordance gating. Shape: ``{'resolved': str, 'closed': str}`` where each value is one of:\n- ``ready`` — disposition is appropriate; render the affordance enabled with the default 'click to confirm' UX.\n- ``needs_info`` — disposition is allowed but the case is partial; user must ADD information (root cause / solution) before transitioning. UX: prompt the user for the missing data. Currently only the Resolve side surfaces this.\n- ``suggests_alternative`` — disposition is allowed but the system recommends the OTHER disposition for this case. UX: warn and offer the alternative; if the user confirms anyway, proceed. Distinct from ``needs_info`` — no data is missing; the user is asked to RE-DIRECT, not to add. Currently only the Close side surfaces this (when the case has root cause + solution → resolving preserves attribution).\n- ``not_eligible`` — disposition is not available; hide the affordance entirely.\n\nDifferent from ``valid_next_states`` — that field is the structural action graph (which edges exist), this field is the content-readiness layer on top.",
        title="Disposition Eligibility",
    )
    latest_evidence: list[EvidenceSummary] | None = Field(
        None, description="Most recent evidence collected (last 5)", title="Latest Evidence"
    )
    next_actions: list[str] | None = Field(
        None, description="Suggested next steps for investigation", title="Next Actions"
    )
    problem_statement: constr(max_length=1000) | None = Field(
        None,
        description="Confirmed problem statement carried over from INQUIRY (sourced from case.description).",
        title="Problem Statement",
    )
    problem_verification: ProblemVerificationData | None = Field(
        None, description="Problem verification details (urgency, severity, impact)"
    )
    progress: InvestigationProgressSummary = Field(
        ..., description="Milestone-based progress tracking"
    )
    progress_transparency: ProgressTransparencyInfo | None = Field(
        None,
        description="Progress transparency state. Present when investigation has stalled and agent is surfacing milestone dependencies.",
    )
    state: Literal["investigating"] = Field(
        "investigating", description="Always 'investigating' for this response type", title="State"
    )
    title: constr(max_length=200) = Field(..., description="Case title", title="Title")
    updated_at: AwareDatetime = Field(..., description="Last update timestamp", title="Updated At")
    uploaded_files_count: int | None = Field(
        0, description="Number of uploaded files", title="Uploaded Files Count"
    )
    valid_next_states: list[str] | None = Field(
        None,
        description="Allowed state transitions from current state for user-initiated changes",
        title="Valid Next States",
    )
    working_conclusion: WorkingConclusionSummary | None = Field(
        None, description="Agent's current understanding of the problem"
    )


class ReportGenerationResponse(BaseModel):
    case_id: str = Field(..., description="Case identifier", title="Case Id")
    remaining_regenerations: conint(ge=0, le=5) = Field(
        ...,
        description="Number of regenerations remaining (max 5 per report type)",
        title="Remaining Regenerations",
    )
    reports: list[CaseReport] = Field(..., description="Generated reports", title="Reports")
